names = ['Nikita',
         'Dima',
         'Alex',
         'Sergey',
         'Alexander',
         'Andrei',
         'Vlad',
         'Sasha',
         'Artyom',
         'Ivan',
         'Anton',
         'Dmitry',
         'Max',
         'Kirill',
         'Igor',
         'Andrew',
         'Roman',
         'Oleg',
         'Pavel',
         'Ilya',
         'Denis',
         'Ruslan',
         'Vladislav',
         'Vladimir',
         'Alexey',
         'Danil',
         'Yaroslav',
         'Konstantin',
         'Pasha',
         'Kolya',
         'Anatoly',
         'Bogdan',
         'Fedor']

ranks = ['PVT',
         'PFC',
         'JSGT',
         'SGT',
         'SSGT']

camo_patterns = ['3-TsV',
                 'Flora',
                 'Berezhka',
                 'TTsKO',
                 'SMK',
                 'Kamush',
                 'Reed',
                 'KKO']

helmets = [('Sphere', 1, ('Head')),
           ('Sphere-S', 2, ('Head')),
           ('Maska-1', 2, ('Head', 'Face')),
           ('Altyn', 2, ('Head', 'Face')),
           ('Tanker', 0, ('Head')),
           ('Cap', 0, ('Head')),
           ('Boonie', 0, ('Head')),
           ('Officers Cap', 0, ('Head')),
           ('Chechenka', 0, ('Head', 'Face'))]
